### ISSUE TITLE
Playtest report

### ISSUE THREAD

**Issue by sajattack** [psbleep/crsh_server#101]
Hey, cool game. I'm really interested in hacker movies and games like Hackers and HackNet, so this was cool to see. A few issues I noticed, the download command doesn't seem to have a manpage, and sometimes freezes the game when I use it. It's a bit hard to progress without reading the source, like figuring out the user for the 1337_2 account, and I think I broke the game by getting admin and shutting down the 1337 box. Not sure if this is a desired outcome or not. I understand the game is work in progress, just thought I would give you a quick rundown of how my game went. Thanks for making it.

**Comment by sajattack** [comment]
Oh, I forgot to mention, I made a 2nd account to see if the 1337 server would be down for them as well (it was), and by making the 2nd user I lost the token for the 1st one.

**Comment by psbleep** [comment]
@sajattack Thanks for playing and for leaving feedback! You are the first person to look at the game, apart from a few friends.

I will definitely look into the bug with the `download` command freezing the game (and including a man page for it). Your point is also well taken that the in-game instructions/clues are inadequate for figuring out how to play currently.

Switching accounts on the client should be possible by running `crsh setup` and not choosing to create a new user when prompted, then putting in the username/password for the account you created previously. But the CLI could definitely be improved there.

You shutting down the 1337 server points at a general issue with the game that I have been thinking about. Much of the game world state should be shared across players, so that it is possible to hack other players, compete to be the first to steal lucrative corporate secrets, etc. But other aspects of the game world state should be player-specific, such as this training mission server. You shutting it down would ideally not impact other players.

Thanks again for checking out the game and I hope you will give it another look as it evolves! I will have more time to work on it again soon, and hope to have a minimal playable version done by the end of the year.

**Comment by sajattack** [comment]
It was the least I could do. You've helped a lot of people with your former career and I'm so happy we share this common interest in open source software. Let me know if there's any way I can help.

**Comment by sajattack** [comment]
❤️💪👊
